name: eda-streamlit-fastapi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==3.7.1
      - attrs==23.1.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - dacite==1.8.1
      - fastapi==0.105.0
      - fonttools==4.47.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h11==0.14.0
      - htmlmin==0.1.12
      - idna==3.6
      - imagehash==4.3.1
      - importlib-metadata==6.11.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - missingno==0.5.2
      - multimethod==1.10
      - networkx==3.2.1
      - numba==0.58.1
      - numpy==1.25.2
      - packaging==23.2
      - pandas==2.1.4
      - patsy==0.5.4
      - phik==0.12.3
      - pillow==10.1.0
      - plotly==5.18.0
      - protobuf==4.25.1
      - pyarrow==14.0.2
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pywavelets==1.5.0
      - pyyaml==6.0.1
      - referencing==0.32.0
      - requests==2.31.0
      - rich==13.7.0
      - rpds-py==0.15.2
      - scikit-learn==1.4.1.post1
      - scipy==1.11.4
      - seaborn==0.12.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - starlette==0.27.0
      - statsmodels==0.14.1
      - streamlit==1.29.0
      - tangled-up-in-unicode==0.2.0
      - tenacity==8.2.3
      - threadpoolctl==3.3.0
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.4
      - typeguard==4.1.5
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==2.1.0
      - uvicorn==0.25.0
      - validators==0.22.0
      - visions==0.7.5
      - watchdog==3.0.0
      - wordcloud==1.9.3
      - ydata-profiling==4.6.3
      - zipp==3.17.0
