name: eda-streamlit-fastapi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - altair==5.2.0
      - anyio==3.7.1
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - fastapi==0.105.0
      - fonttools==4.47.0
      - idna==3.6
      - importlib-metadata==6.11.0
      - jinja2==3.1.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - numpy==1.26.2
      - packaging==23.2
      - pandas==2.1.4
      - pillow==10.1.0
      - plotly==5.18.0
      - protobuf==4.25.1
      - pyarrow==14.0.2
      - pydeck==0.8.1b0
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - referencing==0.32.0
      - requests==2.31.0
      - rpds-py==0.15.2
      - six==1.16.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - streamlit==1.29.0
      - tenacity==8.2.3
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.4
      - tzlocal==5.2
      - urllib3==2.1.0
      - validators==0.22.0
      - watchdog==3.0.0
      - zipp==3.17.0
